// interface-vue/src/App.vue
<script lang="ts">
import { ref, onMounted } from 'vue'

import { MetaMaskInpageProvider } from '@metamask/providers'

declare global {
  interface Window {
    ethereum?: MetaMaskInpageProvider
  }
}

import { ethers } from 'ethers'
import PokemonCards from '../../contracts/out/PokemonCards.sol/PokemonCards.json'
import TradingPlatform from '../../contracts/out/TradingPlatform.sol/TradingPlatform.json'

import MarketplaceView from './components/MarketplaceView.vue'
import MyCardsView from './components/MyCardsView.vue'
import type { Contract } from 'ethers'
import { markRaw } from 'vue';

export default {
  name: 'App',
  components: {
    MarketplaceView,
    MyCardsView,
  },
  setup() {
    const account = ref<string | null>(null)
    const provider = ref<ethers.providers.Web3Provider | null>(null)
    const pokemonContract = ref<Contract | null>(null)
    const tradingContract = ref<Contract | null>(null)
    const activeTab = ref('marketplace')
    const contractsInitialized = ref(false)

    const connectWallet = async () => {
      try {
        if (window.ethereum) {
          const accounts = await window.ethereum.request({
            method: 'eth_requestAccounts',
          })
          account.value = accounts[0]
          await initializeContracts()
        } else {
          alert('Please install MetaMask!')
        }
      } catch (error) {
        console.error('Error connecting wallet:', error)
      }
    }

    const initializeContracts = async () => {
      if (window.ethereum) {
        provider.value = new ethers.providers.Web3Provider(window.ethereum as MetaMaskInpageProvider)
      } else {
        throw new Error('MetaMask is not installed')
      }
      provider.value = markRaw(provider.value)
      let signer = await provider.value.getSigner()
      signer = markRaw(signer)

      pokemonContract.value = new ethers.Contract(
        '0xaD94c8809A9a070a9DA47C6818c6390A7225D49a',
        PokemonCards.abi,
        signer,
      )

      console.log("here")

      tradingContract.value = new ethers.Contract(
        '0x9A4eE25f90dFdaf3c19e55825f2ed6228d5718Cc',
        TradingPlatform.abi,
        signer,
      )

      contractsInitialized.value = true
    }

    const shortenAddress = (address: string) => {
      return `${address.slice(0, 6)}...${address.slice(-4)}`
    }

    onMounted(() => {
      // Check if already connected
      if (window.ethereum) {
        window.ethereum.request({ method: 'eth_accounts' }).then((accounts: string[]) => {
          if (accounts.length > 0) {
            account.value = accounts[0]
            initializeContracts()
          }
        })
      }
    })

    return {
      account,
      activeTab,
      pokemonContract,
      tradingContract,
      connectWallet,
      shortenAddress,
      contractsInitialized,
    }
  },
}
</script>

<template>
  <div class="min-h-screen bg-gray-100">
    <nav class="bg-white shadow-lg p-4">
      <div class="container mx-auto flex justify-between items-center">
        <h1 class="text-2xl font-bold text-blue-600">Pokémon Card Trading</h1>
        <div
          v-if="!account"
          @click="connectWallet"
          class="cursor-pointer bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
        >
          Connect Wallet
        </div>
        <div v-else class="text-gray-600">
          {{ shortenAddress(account) }}
        </div>
      </div>
    </nav>

    <main class="container mx-auto p-4">
      <!-- Wallet not connected warning -->
      <div v-if="!account" class="text-center py-10">
        <h2 class="text-xl">Please connect your wallet to access the trading platform</h2>
      </div>

      <div v-else>
        <!-- Tabs -->
        <div class="mb-6 border-b border-gray-200">
          <nav class="flex space-x-4">
            <button
              @click="activeTab = 'marketplace'"
              :class="[
                'py-2 px-4',
                activeTab === 'marketplace'
                  ? 'border-b-2 border-blue-500 text-blue-600'
                  : 'text-gray-500',
              ]"
            >
              Marketplace
            </button>
            <button
              @click="activeTab = 'myCards'"
              :class="[
                'py-2 px-4',
                activeTab === 'myCards'
                  ? 'border-b-2 border-blue-500 text-blue-600'
                  : 'text-gray-500',
              ]"
            >
              My Cards
            </button>
          </nav>
        </div>

        <!-- Content -->
        <div v-if="contractsInitialized && activeTab === 'marketplace'">
          <marketplace-view
            :account="account"
            :tradingContract="tradingContract || {}"
            :pokemonContract="pokemonContract || {}"
          />
        </div>
        <div v-else>
          <my-cards-view
            :account="account"
            :tradingContract="tradingContract || {}"
            :pokemonContract="pokemonContract || {}"
          />
        </div>
      </div>
    </main>
  </div>
</template>

// interface/src/App.jsx
import React, { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom';
import './App.css';

// Components
import Home from './components/Home';
import MyCollection from './components/MyCollection';
import Marketplace from './components/MarketPlace';
import MintPokemonCard from './components/MintPokemonCard';

// Contract ABIs
import PokemonCardsABI from '../../contracts/out/PokemonCards.sol/PokemonCards.json';
import TradingPlatformABI from '../../contracts/out/TradingPlatform.sol/TradingPlatform.json';

const CONTRACT_ADDRESSES = {
  pokemonCards: '0xC3062018402e0A74f74090C1e8c420aDb7452f94',
  tradingPlatform: '0xE7bEC2A1377d671B06a148EB3cc257fF0197FAb7',
};

function App() {
  const [provider, setProvider] = useState(null);
  const [signer, setSigner] = useState(null);
  const [account, setAccount] = useState(null);
  const [pokemonCards, setPokemonCards] = useState(null);
  const [tradingPlatform, setTradingPlatform] = useState(null);
  const [listings, setListings] = useState([]);

  const connectWallet = async () => {
    if (window.ethereum) {
      try {
        await window.ethereum.request({ method: 'eth_requestAccounts' });
        const web3Provider = new ethers.BrowserProvider(window.ethereum);
        const signer = await web3Provider.getSigner();
        const account = await signer.getAddress();

        const pokemonCardsContract = new ethers.Contract(
          CONTRACT_ADDRESSES.pokemonCards,
          PokemonCardsABI.abi,
          signer
        );

        const tradingPlatformContract = new ethers.Contract(
          CONTRACT_ADDRESSES.tradingPlatform,
          TradingPlatformABI.abi,
          signer
        );

        setProvider(web3Provider);
        setSigner(signer);
        setAccount(account);
        setPokemonCards(pokemonCardsContract);
        setTradingPlatform(tradingPlatformContract);

        // Listen for account changes
        window.ethereum.on('accountsChanged', (accounts) => {
          setAccount(accounts[0]);
        });
      } catch (error) {
        console.error(error);
      }
    }
  };

  useEffect(() => {
    const loadListings = async () => {
      if (tradingPlatform) {
        const listedEvents = await tradingPlatform.queryFilter('Listed');
        const activeListings = await Promise.all(
          listedEvents.map(async (event) => {
            const listing = await tradingPlatform.listings(event.args.tokenId);
            return { ...listing, tokenId: event.args.tokenId };
          })
        );
        setListings(activeListings.filter((l) => l.active));
      }
    };
    loadListings();
  }, [tradingPlatform]);

  return (
    <Router>
      <div className="app-container">
        {/* Top Navigation Bar */}
        <div className="navbar">
          <h1>Pokémon Trading</h1>
          <nav>
            <Link to="/">Home</Link>
            <Link to="/market-place">Market Place</Link>
            <Link to="/my-collection">My Collection</Link>
            <Link to="/mint-card">Mint Card</Link> {/* Add Mint Card link */}
          </nav>
          <div className="wallet-info">
            {!account ? (
              <button onClick={connectWallet} className="connect-button">
                Connect Wallet
              </button>
            ) : (
              <button className="connected-address" disabled>
                {`${account.slice(0, 6)}...${account.slice(-4)}`}
              </button>
            )}
          </div>
        </div>

        {/* Main Content */}
        <div className="main-content">
          <Routes>
            <Route
              path="/"
              element={
                <Home
                  listings={listings}
                  pokemonCards={pokemonCards}
                  tradingPlatform={tradingPlatform}
                  account={account}
                />
              }
            />
            <Route
              path="/my-collection"
              element={
                <MyCollection
                  pokemonCards={pokemonCards}
                  tradingPlatform={tradingPlatform} // Pass the tradingPlatform prop
                  account={account}
                />
              }
            />
            <Route
              path="/market-place"
              element={
                <Marketplace
                  pokemonCards={pokemonCards}
                  tradingPlatform={tradingPlatform}
                  account={account}
                />
              }
            />
            <Route
              path="/mint-card"
              element={
                <MintPokemonCard
                  pokemonCards={pokemonCards}
                  account={account}
                />
              }
            />
          </Routes>
        </div>
      </div>
    </Router>
  );
}

export default App;
